spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alerts
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083
client:
  service:
    url: http://localhost:8081/api/v1/clients